#pragma once

enum CameraCallFunction {
	CALLABLE_ID_PINHOLE,
	NUM_CALLABLE_CAMERA
};

enum TexCallFunction {
	CALLABLE_CHECKEDTEX,
	CALLABLE_CONSTANTTEX,
	CALLABLE_IMAGETEX,
	CALLABLE_NOISETEX,
	CALLABLE_NULLTEX,
	NUM_CALLABE_TEX_IDS
};

enum MatCallFunction {
	CALLABLE_ID_LIGHT_DIFFUSE,
	CALLABLE_ID_DIELECTRIC,
	CALLABLE_ID_ISOTROPIC,
	CALLABLE_ID_LAMBERTIAN,
	CALLABLE_ID_METAL,
	CALLABLE_ID_NORMAL,
	NUM_CALLABLE_MAT_IDS
};

enum PDFCallFunction {
	CALLABLE_ID_cosineGenerate,
	CALLABLE_ID_mixtureBIAS_generate,
	CALLABLE_ID_mixture_generate,

	CALLABLE_ID_rect_X_generate,
	CALLABLE_ID_rect_Y_generate,
	CALLABLE_ID_rect_Z_generate,
	CALLABLE_ID_cosineValue,
	CALLABLE_ID_mixtureBIAS_value,
	CALLABLE_ID_mixture_value,
	CALLABLE_ID_rect_x_value,
	CALLABLE_ID_rect_y_value,
	CALLABLE_ID_rect_z_value,
	CALLABLE_ID_LIGHT_SAMPLE_PDF,
	CALLABLE_ID_LIGHT_SAMPLE_DIELECT_PDF,
	CALLABLE_ID_LIGHT_SAMPLE_METAL_PDF,
	NUM_CALLABLE_PDF_IDS
};